"""
Script for converting a hdf5 dataset (generated by RobotGPT's modified version of Isaac Lab's record_demo.py script) to the LeRobot format expected by openpi.

Usage:
uv run convert_hdf5_to_openpi_lerobot.py --data_dir /path/to/your/data

The resulting dataset will get saved to the $HF_LEROBOT_HOME directory.


This script is based on the "examples/libero/convert_libero_data_to_lerobot.py" script of the openpi repository.

Modifications: Copyright (c) 2026 ronypepper.

License: Apache 2.0
"""

import ast
import dataclasses
import pathlib
import shutil
from itertools import islice

import h5py
import numpy as np
import tyro
from hdf5_dataset_interfaces import get_hdf5_dataset_interface_fcts
from lerobot.common.datasets.lerobot_dataset import HF_LEROBOT_HOME, LeRobotDataset
from tqdm import tqdm


@dataclasses.dataclass
class Args:
    """Arguments for the conversion script."""

    # Path to input hdf5 dataset.
    dataset: str = "./robotgpt_outputs/datasets/hdf5/dataset.hdf5"

    # Hugging face username.
    hf_user: str | None = None

    # Name of the ouput dataset. If None or empty string, the input dataset's name will be used.
    output_name: str | None = None

    # Push converted dataset to hugging face hub.
    push_to_hub: bool = False

    # Robot type - must be an option in HDF5_DATASET_INTERFACE_FCTS of hdf5_dataset_interfaces.py.
    robot_type: str | None = None

    # Number of episodes to write into converted dataset. 0 means all episodes.
    num_episodes: int = 0


def main(args: Args):
    # Process arguments
    if args.hf_user is None:
        raise ValueError("hf_user must be set.")

    dataset_path = (
        pathlib.Path(args.dataset).expanduser().resolve()
    )  # h5py seems to cannot expand ~ to home directory by itself
    if not dataset_path.exists():
        raise ValueError(f"dataset path ({args.dataset}) does not exist.")
    args.dataset = str(dataset_path)
    if not h5py.is_hdf5(args.dataset):
        raise ValueError(f"dataset ({args.dataset}) is not a valid .hdf5 dataset.")

    if args.output_name is None or args.output_name == "":
        args.output_name = pathlib.Path(args.dataset).stem

    # Get dataset interface functions based on robot type
    get_data_dimensions_fct, process_hdf5_frame_fct = get_hdf5_dataset_interface_fcts(args.robot_type)

    # Clean up any existing dataset in the output directory
    repo_name = args.hf_user + "/" + args.output_name
    output_path = HF_LEROBOT_HOME / repo_name
    if output_path.exists():
        shutil.rmtree(output_path)

    # Load input dataset
    with h5py.File(args.dataset, "r") as hdf5_dataset:
        # Extract metadata from input dataset
        env_args = ast.literal_eval(
            hdf5_dataset["data"].attrs["env_args"]
        )  # Need to convert to dict from string representation here
        fps = int(1.0 / (env_args["sim_args"]["dt"] * env_args["sim_args"]["decimation"]))
        prompt = env_args["prompt"]

        # Create LeRobot dataset, define features to store
        # OpenPi assumes that proprio is stored in `state` and actions in `action`
        # LeRobot assumes that dtype of image data is `image`
        dimensions = get_data_dimensions_fct()
        lerobot_dataset = LeRobotDataset.create(
            repo_id=repo_name,
            robot_type=args.robot_type,
            fps=fps,
            features={
                "table_img": {
                    "dtype": "image",
                    "shape": (dimensions["img_height"], dimensions["img_width"], 3),
                    "names": ["height", "width", "channel"],
                },
                "wrist_img": {
                    "dtype": "image",
                    "shape": (dimensions["img_height"], dimensions["img_width"], 3),
                    "names": ["height", "width", "channel"],
                },
                "state": {
                    "dtype": "float32",
                    "shape": (dimensions["state"],),
                    "names": ["state"],
                },
                "actions": {
                    "dtype": "float32",
                    "shape": (dimensions["actions"],),
                    "names": ["actions"],
                },
            },
            image_writer_threads=10,
            image_writer_processes=5,
        )

        # Parse and write requested number of demonstrations to the LeRobot dataset
        hdf5_demos = hdf5_dataset["data"].values()

        if args.num_episodes > 0:
            total_episodes = args.num_episodes
            hdf5_demos = islice(hdf5_demos, args.num_episodes)
        else:
            total_episodes = len(hdf5_dataset["data"])

        for demo in tqdm(hdf5_demos, total=total_episodes):
            for step in tqdm(range(demo.attrs["num_samples"]), leave=False):
                frame = process_hdf5_frame_fct(demo, step)
                frame["task"] = prompt
                lerobot_dataset.add_frame(frame)
            lerobot_dataset.save_episode()

    # Optionally push to the Hugging Face Hub
    if args.push_to_hub:
        lerobot_dataset.push_to_hub(
            tags=["libero", "panda", "rlds"],
            private=False,
            push_videos=True,
            license="apache-2.0",
        )


if __name__ == "__main__":
    main(tyro.cli(Args))
