"""
Script for converting a hdf5 dataset (generated by RobotGPT's modified version of Isaac Lab's record_demo.py script) to the LeRobot format expected by openpi.
This script is based on the "examples/libero/convert_libero_data_to_lerobot.py" script of the openpi repository.

Usage:
uv run convert_hdf5_to_openpi_lerobot.py --data_dir /path/to/your/data

The resulting dataset will get saved to the $HF_LEROBOT_HOME directory.
"""

import ast
import dataclasses
import pathlib
import shutil

import h5py
from lerobot.common.datasets.lerobot_dataset import HF_LEROBOT_HOME
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
import numpy as np
from tqdm import tqdm
import tyro

ROBOT_TYPES = ("franka_single_arm",)


@dataclasses.dataclass
class Args:
    """Arguments for the conversion script."""

    # Path to input hdf5 dataset.
    dataset: str = "./datasets/dataset.hdf5"

    # Hugging face username.
    hf_user: str | None = None

    # Name of the ouput dataset. If None, the input dataset's name will be used.
    output_name: str | None = None

    # Push converted dataset to hugging face hub.
    push_to_hub: bool = False

    # Robot type - must be one of ROBOT_TYPES (is also entered into LeRobot dataset).
    robot_type: str = None


def main(args: Args):
    # Process arguments
    if args.hf_user is None:
        raise ValueError("hf_user must be set.")

    dataset_path = (
        pathlib.Path(args.dataset).expanduser().resolve()
    )  # h5py cannot (seemingly) expand ~ to home directory by itself
    if not dataset_path.exists():
        raise ValueError(f"dataset path ({args.dataset}) does not exist.")
    args.dataset = str(dataset_path)
    if not h5py.is_hdf5(args.dataset):
        raise ValueError(f"dataset ({args.dataset}) is not a valid .hdf5 dataset.")

    if args.output_name is None:
        args.output_name = pathlib.Path(args.dataset).stem

    if args.robot_type not in ROBOT_TYPES:
        raise ValueError(f"robot_type must be one of {ROBOT_TYPES}.")

    # Assign dataset parser functions based on robot type
    get_dimensions_fct, extract_frame_fct = None, None
    if args.robot_type == "franka_single_arm":
        get_dimensions_fct, extract_frame_fct = get_dimensions_franka_single_arm, extract_frame_franka_single_arm

    if get_dimensions_fct is None or extract_frame_fct is None:
        raise ValueError(f"No dataset parser functions defined for valid robot type {args.robot_type}.")

    # Clean up any existing dataset in the output directory
    repo_name = args.hf_user + "/" + args.output_name
    output_path = HF_LEROBOT_HOME / repo_name
    if output_path.exists():
        shutil.rmtree(output_path)

    # Load input dataset
    with h5py.File(args.dataset, "r") as hdf5_dataset:
        # Extract metadata from input dataset
        env_args = ast.literal_eval(
            hdf5_dataset["data"].attrs["env_args"]
        )  # Need to convert to dict from string representation here
        fps = int(1.0 / (env_args["sim_args"]["dt"] * env_args["sim_args"]["decimation"]))
        prompt = env_args["prompt"]

        # Create LeRobot dataset, define features to store
        # OpenPi assumes that proprio is stored in `state` and actions in `action`
        # LeRobot assumes that dtype of image data is `image`
        dimensions = get_dimensions_fct()
        lerobot_dataset = LeRobotDataset.create(
            repo_id=repo_name,
            robot_type=args.robot_type,
            fps=fps,
            features={
                "table_img": {
                    "dtype": "image",
                    "shape": (dimensions["img_height"], dimensions["img_width"], 3),
                    "names": ["height", "width", "channel"],
                },
                "wrist_img": {
                    "dtype": "image",
                    "shape": (dimensions["img_height"], dimensions["img_width"], 3),
                    "names": ["height", "width", "channel"],
                },
                "state": {
                    "dtype": "float32",
                    "shape": (dimensions["state"],),
                    "names": ["state"],
                },
                "actions": {
                    "dtype": "float32",
                    "shape": (dimensions["actions"],),
                    "names": ["actions"],
                },
            },
            image_writer_threads=10,
            image_writer_processes=5,
        )

        # Pare and write demonstrations to the LeRobot dataset
        for demo in tqdm(hdf5_dataset["data"].values()):
            for step in tqdm(range(demo.attrs["num_samples"])):
                frame = extract_frame_fct(demo, step)
                frame["task"] = prompt
                lerobot_dataset.add_frame(frame)
            lerobot_dataset.save_episode()

    # # Optionally push to the Hugging Face Hub
    # if args.push_to_hub:
    #     dataset.push_to_hub(
    #         tags=["libero", "panda", "rlds"],
    #         private=False,
    #         push_videos=True,
    #         license="apache-2.0",
    #     )


def get_dimensions_franka_single_arm():
    return {
        "actions": 8,
        "state": 8,
        "img_width": 224,
        "img_height": 224,
    }


def extract_frame_franka_single_arm(demo: h5py.Group, step: int) -> dict:
    # Pi0 models are trained for gripper positions in [0.0, 1.0], with 0.0 corresponding to fully open and 1.0 corresponding to fully closed.
    # Observations in the dataset are in [0.0, 0.04], with 0.0 corresponding to fully closed and 0.04 corresponding to fully open.
    # Therefore we adjust the gripper observation to fit the Pi0 models' format. For actions, we can extract the gripper command directly in this format.
    state_obs = demo["obs"]["joint_pos"][step]
    joint_pos_obs = state_obs[0:7]
    gripper_obs = (state_obs[7:8] - 0.04) / 0.04
    state_obs = np.concatenate((joint_pos_obs, gripper_obs))

    joint_pos_actions = demo["processed_actions"][step][:7]
    gripper_action = demo["actions"][step][7:8]
    actions = np.concatenate((joint_pos_actions, gripper_action))
    return {
        "table_img": demo["obs"]["table_img"][step],
        "wrist_img": demo["obs"]["wrist_img"][step],
        "state": state_obs,
        "actions": actions,
    }


if __name__ == "__main__":
    main(tyro.cli(Args))
